version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - 3001:3001
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
